### ISSUE TITLE
py2-pip (no such package)

### ISSUE THREAD

**Issue by samcro1967** [itzg/docker-elasticsearch-curator#2]
Looks like this image will no longer build due to deprecated packages.  Any chance you can update?  I can't find another container out there that you just install and forget about it.  All the other ones install the CLI and then you have to manually run or schedule to run.

```
Sending build context to Docker daemon  4.608kB
Step 1/6 : FROM alpine
 ---> 6dbb9cc54074
Step 2/6 : RUN apk -U add python py2-pip
 ---> Running in 27767b2845b3
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  py2-pip (no such package):
    required by: world[py2-pip]
  python (no such package):
    required by: world[python]
The command '/bin/sh -c apk -U add python py2-pip' returned a non-zero code: 2
```

**Comment by itzg** [comment]
Wow, it's been a while since I updated this one. Let me see if I can revive it.

**Comment by itzg** [comment]
Latest Dockerfile and image now use python3. I also bumped the curator version to 5.8.3.

**Comment by samcro1967** [comment]
Seems to be working like a champ.  Appreciate the update.
